/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/jsx-no-target-blank */
const PrivacyPolicy = () => {
  return (
    <div className="max-w-[92%] lg:max-w-[1200px] mx-auto">
     <h1  className="text-3xl font-bold font-inter my-7">Privacy Policy</h1>
<p  className="text-xl font-bold font-inter my-3">Last updated: February 22, 2024</p>
<div className="text-lg font-medium my-1.5">
<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.</p>
</div>
<h2 className="text-3xl font-bold font-inter my-7">Interpretation and Definitions</h2>
<div className="text-lg font-medium my-1.5">
<h3 className="my-2 font-semibold text-xl">Interpretation</h3>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
</div>
<div className="space-y-4">
<h3 className="my-2 font-semibold text-xl">Definitions</h3>
<p className="font-bold font-inter">For the purposes of this Privacy Policy:</p>
<ul className="space-y-2">
<li>
<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
</li>
<li>
<p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Unity Spark , Level-5, 23, Gulshan, Dhaka-1211.</p>
</li>
<li>
<p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
</li>
<li>
<p><strong>Country</strong> refers to:  Bangladesh</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
</li>
<li>
<p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Website.</p>
</li>
<li>
<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
</li>
<li>
<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
</li>
<li>
<p><strong>Website</strong> refers to Unity Spark, accessible from <a href="https://unity-spark-22122.web.app/" rel="external nofollow noopener" target="_blank">https://unity-spark-22122.web.app/</a></p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
</div>
<h2 className="text-3xl font-bold font-inter my-7">Children's Privacy</h2>
<div className="text-lg font-medium space-y-3">
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
</div>
<h2 className="text-3xl font-bold font-inter my-7">Links to Other Websites</h2>
<div className="text-lg font-medium space-y-3">
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
</div>
<h2 className="text-3xl font-bold font-inter my-7">Changes to this Privacy Policy</h2>
<div className="text-lg font-medium space-y-3">
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
</div>
<h2  className="text-3xl font-bold font-inter my-7">Contact Us</h2>
<div className="text-lg font-medium space-y-3">
<p >If you have any questions about this Privacy Policy, You can contact us:</p>
<ul className="space-y-1.5 mb-3">
<li>
<p>By email: unityspark@gmail.com</p>
</li>
<li>
<p>By visiting this page on our website: <a href="https://unity-spark-22122.web.app/" rel="external nofollow noopener" target="_blank">https://unity-spark-22122.web.app/</a></p>
</li>
</ul>
</div>
    </div>
  );
};

export default PrivacyPolicy;
